<?php for($i=0; $i<3; $i++):?>
  <article class="z-depth-1">
    <h2 class="title">Lorem ipsum dolor sit amet?</h2>
    <div class="article-info">
      <a href="#" class="date"><i class="icon date"></i> 04/03/2016 </a>
      <a href="#" class="author"><i class="icon author"></i> Leandro </a>
      <a href="#" class="comments"><i class="icon comments"></i> 03 Comentários </a>
    </div>
    <figure>
      <img src="https://placeimg.com/640/480/nature" alt="">
    </figure>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id harum officiis ipsam, consequatur enim. Nemo rerum ipsa, excepturi totam voluptatibus! Atque laborum rem aliquid, quam facere accusantium doloremque, velit asperiores, vero architecto fugit magni eligendi at. Consequatur nihil sunt voluptates aliquam nesciunt quae quas magnam molestiae dolor quos, quidem hic excepturi architecto, nostrum cumque, minima ipsa labore. Necessitatibus dicta commodi repudiandae odio, quod deserunt laudantium blanditiis ipsa quae ratione fuga eos nam dolores incidunt quos rerum nulla velit dolorum ullam reiciendis quam quaerat vitae molestias doloremque! Consectetur, fugiat iste molestiae saepe quos veniam, sunt asperiores aliquam, fugit obcaecati autem quae?</p>
    <div class="footer">
      <div class="audio">
        <i class="icon"></i>
        <a href="#" class="listen">Preguiça de ler? Ouça aqui!</a>
        <audio src="" controls="true"></audio>
      </div>
      <a href="#" class="more">Leia Tudo!</a>
    </div>
  </article>
<?php endfor;?>

<div class="pages">
  <div class="prev disabled"></div>
  <div class="next"></div>
</div>
